// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnlnyuvcqvwqfmurhxcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJubG55dXZjcXZ3cWZtdXJoeGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjg0OTEsImV4cCI6MjA2Mjc0NDQ5MX0.N5YuVGt-9afuaDwgtawJKx82QzHgLK4VQA6MPRF2cng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);